<?php 

	include('../class/connect1.php');
	include('../class/class.php');

	$core = Core::getInstance();

	$name = addslashes(strip_tags(trim($_POST['name'])));
	$email = addslashes(strip_tags(trim($_POST['email'])));
	$phn = addslashes(strip_tags(trim($_POST['phn'])));

	//do someting here

	$q = "SELECT * FROM hospital_master WHERE h_name=:h_name AND h_email=:h_email";
	$stmt=$core->dbh->prepare($q);
	$stmt->bindParam(':h_name',$name,PDO::PARAM_STR);
	$stmt->bindParam(':h_email',$email,PDO::PARAM_STR);
	$stmt->execute();
	if($stmt->rowCount() == 0){
	
	//Generate an access token
	$token = bin2hex(openssl_random_pseudo_bytes(20));

	$q1 = "INSERT INTO hospital_master(h_name,h_address,h_phn,h_email,h_username,h_password,access_token,active_flag,isVerified) VALUES(:h_name,'',:h_phn,:h_email,:h_email,'',:access_token,'0','0')";
	$stmt1=$core->dbh->prepare($q1);
	$stmt1->bindParam(':h_name',$name,PDO::PARAM_STR);
	$stmt1->bindParam(':h_email',$email,PDO::PARAM_STR);
	$stmt1->bindParam(':h_phn',$phn,PDO::PARAM_STR);
	$stmt1->bindParam(':access_token',$token,PDO::PARAM_STR);
	$stmt1->execute();


	//send mail for username and password set

		$to_email = $email;
		$subject = 'Nursing Job Portal';
		$message = 'This is a autogenerated mail.';
		$message .= '<br>';
		$message .= 'Please click here to complete the registration<br>';
		$message .= '<a href="registration.html?token='.$token.'"><b>Click Here</b></a>';
		$headers = 'From: nursingjob@gmail.com';
		mail($to_email,$subject,$message,$headers);



?>


<p align="justify">An Email has been sent to your mail id: <b><?php echo $email; ?></b>. Please respond to that mail as soon as possible. The username and password will be sent to you after verification of the documents.</p>


<?php 
	
	}else{

		$r = $stmt->fetchObject();

		if($r->isVerified == 1){
?>

<p align="justify">Account already verfied. <a href="#">Click here</a> to login</p>

<?php 

			}else{

?>

<p align="justify"> A mail has been already sent to your mail: <b><?php echo $r->h_mail; ?></b>. Please check your mail and follow the link for username and password.</p>


<?php 
				}
		}

?>

<br>

<div class="form-group" align="right">
	<a href="register_for_hospital.html"><button class="btn btn-default" type="button" name="cancel" tabindex="5">Goback</button></a>
</div>